name: wakepoint
description: "Location-based alarm app to wake you up before your destination â€” even when offline or asleep."
publish_to: 'none'
version: 0.5.1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_activity_recognition: ^4.0.0
  flutter_background: ^1.3.0+1
  flutter_displaymode: ^0.7.0
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^19.5.0
  fluttertoast: ^9.0.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.0
  http: ^1.6.0
  json_annotation: ^4.9.0
  open_location_code: ^1.0.1
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.4
  vibration: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  json_serializable: ^6.11.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf